USE master
GO
IF DB_ID('APD_PHYSICALDES') IS NOT NULL
	DROP DATABASE APD_PHYSICALDES
GO

CREATE DATABASE APD_PHYSICALDES
GO

CREATE TABLE CUSTOMER --LƯU THÔNG TIN KHÁCH HÀNG
(
	CUSTOMER_IDENTIFIER CHAR(10), --INDENTIFIER
	CUSTOMER_TELEPHONENUMBER CHAR(10),
	CUSTOMER_NAME VARCHAR(30),
	CUSTOMER_ADDRESS VARCHAR(30),
	CUSTOMER_CITY VARCHAR(30),
	CUSTOMER_STATE VARCHAR(30),
	CUSTOMER_ZIPCODE VARCHAR(10),
	CUSTOMER_CREDITRATING VARCHAR(10), --EXCELLENT/ GOOD/ FAIR/ POOR: ĐIỂM TÍN DỤNG

	CONSTRAINT PK_CUSTOMER
	PRIMARY KEY (CUSTOMER_IDENTIFIER)
)

CREATE TABLE CREDIT_CARD --LƯU THÔNG TIN THẺ TÍN DỤNG CỦA KHÁCH HÀNG
(
	CUSTOMER_CREDITCARD_NUMBER VARCHAR(20), --INDENTIFIER
	CUSTOMER_CREDITCARD_NAME CHAR(30), --NAPAS/ DEBIT VISA/ DEBIT MASTER/ CREDIT VISA/ CREDIT MASTER
	CUSTOMERIDENTIFIER CHAR(10), --FOREIGN KEY

	CONSTRAINT PK_CREDIT_CARD
	PRIMARY KEY (CUSTOMER_CREDITCARD_NUMBER),
	CONSTRAINT FK_CREDIT_CARD_CUSTOMER
	FOREIGN KEY (CUSTOMERIDENTIFIER) REFERENCES CUSTOMER
)

CREATE TABLE ORDERS --LƯU THÔNG TIN ĐƠN HÀNG CỦA KHÁCH HÀNG
(
	ORDER_NUMBER CHAR(10),
	CUSTOMER_PHONENUMBER CHAR(10),
	CUSTOMER_IDENTIFIER CHAR(10),
	ORDERDATE DATE,
	SHIPPING_ADDRESS VARCHAR(30),
	SHIPPING_CITY VARCHAR(30),
	SHIPPING_STATE VARCHAR(30),
	SHIPPING_ZIPCODE VARCHAR(10),
	CUSTOMER_CREDITCARD_NUMBER VARCHAR(20),
	SHIPPING_DATE DATE,
	--derived attribute
	TOTAL_PRICE FLOAT,

	CONSTRAINT PK_ORDERS
	PRIMARY KEY (ORDER_NUMBER),

	CONSTRAINT FK_ORDERED_ITEM_CREDIT_CARD		
	FOREIGN KEY ( CUSTOMER_CREDITCARD_NUMBER)
	REFERENCES CREDIT_CARD,

	CONSTRAINT FK_ORDERED__CUSTOMER	
	FOREIGN KEY (CUSTOMER_IDENTIFIER)
	REFERENCES CUSTOMER,
)

CREATE TABLE ADVERTISED_ITEM
(
	ITEM_NUMBER CHAR(10),
	ITEM_DESCRIPTION VARCHAR(100),
	ITEM_DEPARTMENT VARCHAR(20),
	ITEM_WEIGHT FLOAT,
	ITEM_COLOR VARCHAR(10),
	ITEM_PRICE	FLOAT,

	CONSTRAINT PK_ADVERTISED_ITEM
	PRIMARY KEY (ITEM_NUMBER)
)

CREATE TABLE SUPPLIER
(
	SUPPLIER_ID CHAR(10),
	SUPPLIER_NAME VARCHAR(20),
	SUPPLIER_ADDRESS VARCHAR(30),
	SUPPLIER_CITY VARCHAR(30),
	SUPPLIER_STATE VARCHAR(30),
	SUPPLIER_ZIPCODE VARCHAR(10),

	CONSTRAINT PK_SUPPLIER
	PRIMARY KEY (SUPPLIER_ID)
)

CREATE TABLE ORDERED_ITEM
(
	ITEM_NUMBER CHAR(10),
	ORDER_NUMBER CHAR(10),
	QUANTITY_ORDERED TINYINT,
	SELLING_PRICE FLOAT,
	SHIPPING_DATE DATE,

	CONSTRAINT PK_ORDERED_ITEM
	PRIMARY KEY (ITEM_NUMBER, ORDER_NUMBER),

	CONSTRAINT FK_ORDERED_ITEM_ORDER_
	FOREIGN KEY (ORDER_NUMBER)
	REFERENCES ORDERS,

	CONSTRAINT FK_ORDERED_ITEM_ADVERTISED_ITEM
	FOREIGN KEY (ITEM_NUMBER)
	REFERENCES ADVERTISED_ITEM,

)

CREATE TABLE RESTOCK_ITEM
(
	ITEM_NUMBER CHAR(10),
	SUPPLIER_ID CHAR(10),
	PURCHARSE_PRICE FLOAT,

	CONSTRAINT PK_RESTOCK_ITEM
	PRIMARY KEY (ITEM_NUMBER, SUPPLIER_ID),

	CONSTRAINT FK_RESTOCK_ITEM_ADVERTISED_ITEM
	FOREIGN KEY (ITEM_NUMBER)
	REFERENCES ADVERTISED_ITEM,

	CONSTRAINT FK_RESTOCK_ITEM_SUPPLIER
	FOREIGN KEY (SUPPLIER_ID)
	REFERENCES SUPPLIER,
)
GO

--B. INTEGITY CONSTRAINT
--Thuộc tính suy diễn TOTAL_PRICE của bảng ORDERS phụ thuộc vào thuộc tính QUANTITY_ORDERED và SELLING_PRICE của bảng ORDERED_ITEM
create TRIGGER TR_TOTAL_PRICE
ON ORDERED_ITEM
AFTER INSERT, UPDATE 
AS
BEGIN
	UPDATE ORDERS
	SET TOTAL_PRICE = (SELECT SUM(QUANTITY_ORDERED * SELLING_PRICE)
						FROM ORDERED_ITEM
						WHERE ORDER_NUMBER = INSERTED.ORDER_NUMBER)
END

--

--INDEXES 

--SELECT QUERY
--1. Đối với một đơn đặt hàng của khách hàng cụ thể, tổng chi phí đơn hàng là bao nhiêu?
SELECT ORDER_NUMBER, CUSTOMER_IDENTIFIER, TOTAL_PRICE
FROM ORDERS
WHERE ORDER_NUMBER = 'O0001'

--2. Đối với một sản phẩm quảng cáo cụ thể, giá thấp nhất mà nhà cung cấp hiện đang cung cấp là bao nhiêu?
SELECT ITEM_NUMBER, SUPPLIER_ID, MIN(PURCHARSE_PRICE)
FROM RESTOCK_ITEM
--WHERE ITEM_NUMBER = 'I0001'

--3. Khi thông tin khách hàng được truy xuất, bao gồm tất cả các số thẻ tín dụng của họ.
SELECT C.CUSTOMER_IDENTIFIER, C.CUSTOMER_TELEPHONENUMBER, C.CUSTOMER_NAME, C.CUSTOMER_ADDRESS, C.CUSTOMER_CITY, C.CUSTOMER_STATE, C.CUSTOMER_ZIPCODE, C.CUSTOMER_CREDITRATING, O.CUSTOMER_CREDITCARD_NUMBER
FROM CUSTOMER C JOIN ORDERS O ON C.CUSTOMER_IDENTIFIER = O.CUSTOMER_IDENTIFIER

